export const parallelUniverseDesignSystemRegistry = {
  id: 'parallel-universe-novel-ui',
  title: '平行宇宙小说 UI Design System',
  shell: {
    component: '@/components/design-system/ParallelUniverseShell',
    requiredRailOrder: ['发现', '阅读', '书城', '会员'],
    rule: 'Reader-facing product pages share the public rail. Local Creator App remains a localhost author surface and must not become a public web backend.',
  },
  primitives: [
    { name: 'Button', path: '@/components/ui/button', source: 'shadcn-compatible' },
    { name: 'Badge', path: '@/components/ui/badge', source: 'shadcn-compatible' },
    { name: 'Card', path: '@/components/ui/card', source: 'shadcn-compatible' },
    { name: 'Input', path: '@/components/ui/input', source: 'shadcn-compatible' },
    { name: 'Textarea', path: '@/components/ui/textarea', source: 'shadcn-compatible' },
    { name: 'Label', path: '@/components/ui/label', source: 'shadcn-compatible' },
    { name: 'LiquidGlass', path: '@/components/ui/liquid-glass', source: 'shadcn-compatible-custom' },
    { name: 'Dialog', path: '@/components/ui/dialog', source: 'radix-shadcn-compatible' },
    { name: 'AlertDialog', path: '@/components/ui/alert-dialog', source: 'radix-shadcn-compatible' },
    { name: 'DropdownMenu', path: '@/components/ui/dropdown-menu', source: 'radix-shadcn-compatible' },
    { name: 'Alert', path: '@/components/ui/alert', source: 'shadcn-cli' },
    { name: 'Checkbox', path: '@/components/ui/checkbox', source: 'shadcn-cli' },
    { name: 'Collapsible', path: '@/components/ui/collapsible', source: 'shadcn-cli' },
    { name: 'ScrollArea', path: '@/components/ui/scroll-area', source: 'shadcn-cli' },
    { name: 'Select', path: '@/components/ui/select', source: 'shadcn-cli' },
    { name: 'Separator', path: '@/components/ui/separator', source: 'shadcn-cli' },
    { name: 'Sheet', path: '@/components/ui/sheet', source: 'shadcn-cli' },
    { name: 'Table', path: '@/components/ui/table', source: 'shadcn-cli' },
    { name: 'Tabs', path: '@/components/ui/tabs', source: 'shadcn-cli' },
    { name: 'Tooltip', path: '@/components/ui/tooltip', source: 'shadcn-cli' },
  ],
  patterns: [
    { name: 'Panel', path: '@/components/design-system/Panel', surfaces: ['all'], uses: ['LiquidGlass'] },
    { name: 'UniverseDepth', path: '@/components/design-system/UniverseDepth', surfaces: ['discover', 'library', 'reader'], uses: ['LiquidGlass'] },
    { name: 'WorldlineConstellation', path: '@/components/design-system/UniverseDepth', surfaces: ['discover', 'library', 'reader'] },
    { name: 'PageHeader', path: '@/components/design-system/PageHeader', surfaces: ['discover', 'library', 'creator', 'studio', 'settings', 'billing'] },
    { name: 'BookCard', path: '@/components/design-system/BookCard', surfaces: ['discover', 'library', 'template-detail'] },
    { name: 'TopicFilterBar', path: '@/components/design-system/TopicFilterBar', surfaces: ['discover', 'library'] },
    { name: 'RankedWorldList', path: '@/components/design-system/RankedWorldList', surfaces: ['discover', 'library'] },
    { name: 'ReadingPaper', path: '@/components/design-system/ReadingPaper', surfaces: ['reader'] },
    { name: 'ChoiceCard', path: '@/components/design-system/ChoiceCard', surfaces: ['reader', 'choice-result'] },
    { name: 'ReaderRequestComposer', path: '@/components/reader/ReaderRequestComposer', surfaces: ['reader'], uses: ['Card', 'Tabs', 'Textarea', 'Button', 'Alert'] },
    { name: 'ReaderHotRequestList', path: '@/components/reader/ReaderHotRequestList', surfaces: ['reader'], uses: ['Card', 'Badge', 'Button', 'Alert'] },
    { name: 'ReaderReadingToolButton', path: '@/components/reader/ReaderReadingToolButton', surfaces: ['reader'], uses: ['Button'] },
    { name: 'ReaderStoryIndexPanel', path: '@/components/reader/ReaderStoryIndexPanel', surfaces: ['reader'], uses: ['Card', 'Badge', 'Button'] },
    { name: 'ReaderStoryBranchPanel', path: '@/components/reader/ReaderStoryBranchPanel', surfaces: ['reader'], uses: ['Card', 'Badge', 'Button'] },
    { name: 'ReaderStoryProgressPanel', path: '@/components/reader/ReaderStoryProgressPanel', surfaces: ['reader'], uses: ['Card', 'Badge', 'LiquidGlass', 'WorldlineConstellation'] },
    { name: 'ReaderAccountHeroCard', path: '@/components/reader/ReaderAccountHeroCard', surfaces: ['settings'], uses: ['Card', 'Badge'] },
    { name: 'ReaderEntitlementSummaryGrid', path: '@/components/reader/ReaderEntitlementSummaryGrid', surfaces: ['settings'], uses: ['Card', 'Badge'] },
    { name: 'ReaderAccountMergePanel', path: '@/components/reader/ReaderAccountMergePanel', surfaces: ['settings'], uses: ['Card', 'Badge', 'Button', 'Input', 'Label'] },
    { name: 'ReaderAccountStatusGrid', path: '@/components/reader/ReaderAccountStatusGrid', surfaces: ['settings'], uses: ['Card', 'Badge', 'Button'] },
    { name: 'ReaderDataControlPanel', path: '@/components/reader/ReaderDataControlPanel', surfaces: ['settings'], uses: ['Card', 'Badge', 'Button', 'Input'] },
    { name: 'ReaderCheckoutProgressPanel', path: '@/components/reader/ReaderCheckoutProgressPanel', surfaces: ['settings'], uses: ['Card', 'Badge', 'Button'] },
    { name: 'ReaderMembershipPlanPanel', path: '@/components/reader/ReaderMembershipPlanPanel', surfaces: ['settings'], uses: ['Card', 'Badge', 'PlanCard'] },
    { name: 'CreatorShell', path: '@/components/creator/CreatorShell', surfaces: ['creator'], uses: ['LiquidGlass'] },
    { name: 'CreatorConversationWorkspace', path: '@/components/creator/workspace/CreatorConversationWorkspace', surfaces: ['creator'], uses: ['Button', 'Textarea', 'DropdownMenu', 'Badge', 'CreatorConversationTimeline', 'CreatorRecallRail'] },
    { name: 'CreatorConversationTimeline', path: '@/components/creator/workspace/CreatorConversationTimeline', surfaces: ['creator'], uses: ['Button', 'Badge', 'AlertDialog'] },
    { name: 'CreatorRecallRail', path: '@/components/creator/workspace/CreatorRecallRail', surfaces: ['creator'], uses: ['Button', 'Checkbox', 'Badge', 'ScrollArea'] },
    { name: 'CreatorShortcutBar', path: '@/components/creator/workspace/CreatorWorkspaceShell', surfaces: ['creator'], uses: ['Card', 'Button'] },
    { name: 'CreatorWritingWorkspaceFrame', path: '@/components/creator/workspace/CreatorWorkspaceShell', surfaces: ['creator'] },
    { name: 'CreatorCommandCenterFrame', path: '@/components/creator/workspace/CreatorCommandPalette', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorAssistantSidecarFrame', path: '@/components/creator/workspace/CreatorAssistantSidecar', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorCommandCandidateFrame', path: '@/components/creator/workspace/CreatorCommandCandidate', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorGuidedCoachFrame', path: '@/components/creator/workspace/CreatorSocraticPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorStoryHandoffPanel', path: '@/components/creator/workspace/CreatorDraftGuidancePanels', surfaces: ['creator'], uses: ['Button'] },
    { name: 'CreatorReviewDockFrame', path: '@/components/creator/workspace/CreatorReviewDock', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'Tabs'] },
    { name: 'CreatorReviewCommandBar', path: '@/components/creator/workspace/CreatorReviewDock', surfaces: ['creator'], uses: ['Card', 'Input', 'Button', 'Badge'] },
    { name: 'CreatorCreativeReviewDock', path: '@/components/creator/workspace/CreatorReviewDock', surfaces: ['creator'], uses: ['CreatorReviewDockFrame', 'CreatorReviewCommandBar'] },
    { name: 'CreatorQualityIssueCard', path: '@/components/creator/workspace/CreatorQualityPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorStateDiffPanel', path: '@/components/creator/workspace/CreatorImpactPanels', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorBranchSandboxPanel', path: '@/components/creator/workspace/CreatorImpactPanels', surfaces: ['creator'], uses: ['Card', 'Badge', 'Button'] },
    { name: 'CreatorFlightRecorderPanel', path: '@/components/creator/workspace/CreatorImpactPanels', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorParagraphJudgmentFrame', path: '@/components/creator/workspace/CreatorDraftGuidancePanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEditorCursorAssistBar', path: '@/components/creator/workspace/CreatorDraftGuidancePanels', surfaces: ['creator'], uses: ['Button'] },
    { name: 'CreatorParagraphJudgmentPanel', path: '@/components/creator/workspace/CreatorDraftGuidancePanels', surfaces: ['creator'], uses: ['CreatorParagraphJudgmentFrame'] },
    { name: 'CreatorStoryFlowRail', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['CreatorFlowStepper'] },
    { name: 'CreatorTodayNextStepsPanel', path: '@/components/creator/CreatorTodayNextStepsPanel', surfaces: ['creator'], uses: ['Card', 'Alert', 'Button', 'Badge'] },
    { name: 'CreatorStatePanel', path: '@/components/creator/CreatorStatePanel', surfaces: ['creator'], uses: ['LiquidGlass'] },
    { name: 'CreatorActionBar', path: '@/components/creator/CreatorActionBar', surfaces: ['creator'], uses: ['LiquidGlass'] },
    { name: 'CreatorTodayPriorityPanel', path: '@/components/creator/CreatorTodayPriorityPanel', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorDashboardPriorityPanel', path: '@/components/creator/CreatorTodayRoutePanels', surfaces: ['creator'], uses: ['CreatorTodayPriorityPanel'] },
    { name: 'CreatorTodayPathPanel', path: '@/components/creator/CreatorTodayPathPanel', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorTodayEchoStatusPanel', path: '@/components/creator/CreatorTodayEchoStatusPanel', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorTodayContextRail', path: '@/components/creator/CreatorTodayContextRail', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorExternalEchoInboxCard', path: '@/components/creator/CreatorExternalEchoInboxCard', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorExternalEchoDetailPanel', path: '@/components/creator/CreatorExternalEchoDetailPanel', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'Alert'] },
    { name: 'CreatorEchoQueueCard', path: '@/components/creator/CreatorEchoQueueCard', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEchoStatusStrip', path: '@/components/creator/CreatorEchoStatusStrip', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorEchoNextActionPanel', path: '@/components/creator/CreatorEchoDecisionPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEchoDecisionPanel', path: '@/components/creator/CreatorEchoDecisionPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEchoWritingRail', path: '@/components/creator/CreatorEchoWritingRail', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'ConfirmActionDialog'] },
    { name: 'CreatorAuthorDecisionCard', path: '@/components/creator/CreatorAuthorDecisionCard', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorWorkStructureStrip', path: '@/components/creator/CreatorWorkStructureStrip', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorBranchLineCard', path: '@/components/creator/CreatorBranchLineCard', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'ConfirmActionDialog'] },
    { name: 'CreatorPublishBundleContextPanel', path: '@/components/creator/CreatorPublishBundleContextPanel', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorPublishBundleImpactStrip', path: '@/components/creator/CreatorPublishBundleImpactStrip', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorPublishBundleReviewPanel', path: '@/components/creator/CreatorPublishBundleReviewPanel', surfaces: ['creator'], uses: ['Card'] },
    { name: 'CreatorSettingsBoundaryStrip', path: '@/components/creator/CreatorSettingsBoundaryStrip', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorLocalWorkspacePanel', path: '@/components/creator/CreatorLocalWorkspacePanel', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorWorkspacePreferencesPanel', path: '@/components/creator/CreatorWorkspacePreferencesPanel', surfaces: ['creator'], uses: ['Card', 'Checkbox', 'Button', 'ConfirmActionDialog'] },
    { name: 'CreatorSettingsStatusRail', path: '@/components/creator/CreatorSettingsStatusRail', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorFlowStepper', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['Card', 'Button'] },
    { name: 'CreatorNextActionPanel', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorNextBestActionCard', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorCollapsibleOutline', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['Card'] },
    { name: 'CreatorChapterPlannerPanel', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEditorAssistPanel', path: '@/components/creator/workspace/CreatorInlineAssistantPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorGhostCompletionPanel', path: '@/components/creator/workspace/CreatorInlineAssistantPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorInlineReviewPanel', path: '@/components/creator/workspace/CreatorInlineReviewPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEditorReviewRail', path: '@/components/creator/workspace/CreatorInlineReviewPanels', surfaces: ['creator'], uses: ['Card', 'Button'] },
    { name: 'CreatorWritingCommandShelf', path: '@/components/creator/workspace/CreatorInlineAssistantPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'Input'] },
    { name: 'CreatorAgentComposer', path: '@/components/creator/workspace/CreatorAgentAssistantPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'Textarea'] },
    { name: 'CreatorAgentWritingAssistantPanel', path: '@/components/creator/workspace/CreatorAgentAssistantPanels', surfaces: ['creator'], uses: ['CreatorAssistantDock', 'Card', 'Button', 'Badge', 'Textarea'] },
    { name: 'CreatorAssistantDock', path: '@/components/creator/workspace/CreatorAgentAssistantPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'Textarea'] },
    { name: 'CreatorSocraticPlanBoard', path: '@/components/creator/workspace/CreatorSocraticPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorLocalSettingLibrary', path: '@/components/creator/workspace/CreatorSocraticPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEditorDecisionQueuePanel', path: '@/components/creator/workspace/CreatorDecisionPanels', surfaces: ['creator'], uses: ['CreatorDecisionQueue', 'Card', 'Button', 'Badge'] },
    { name: 'CreatorDecisionQueue', path: '@/components/creator/workspace/CreatorDecisionPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorEditorReadinessStrip', path: '@/components/creator/workspace/CreatorProgressPanels', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorProgressRail', path: '@/components/creator/workspace/CreatorProgressPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorMissionProgressRail', path: '@/components/creator/workspace/CreatorProgressPanels', surfaces: ['creator'], uses: ['CreatorProgressRail'] },
    { name: 'CreatorSessionRail', path: '@/components/creator/workspace/CreatorStoryContextPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorStoryMap', path: '@/components/creator/workspace/CreatorStoryContextPanels', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorReaderWishPanel', path: '@/components/creator/workspace/CreatorStoryContextPanels', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorAuthorStatusPanel', path: '@/components/creator/workspace/CreatorCommitPanels', surfaces: ['creator'], uses: ['Card', 'Badge'] },
    { name: 'CreatorDestinationPanel', path: '@/components/creator/workspace/CreatorDestinationPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge', 'Collapsible'] },
    { name: 'CreatorBundleReadinessPanel', path: '@/components/creator/workspace/CreatorDestinationPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'CreatorCanonCommitBar', path: '@/components/creator/workspace/CreatorCommitPanels', surfaces: ['creator'], uses: ['Collapsible', 'Button', 'Badge'] },
    { name: 'CreatorPrivateDraftPanel', path: '@/components/creator/workspace/CreatorPlanningPanels', surfaces: ['creator'], uses: ['Card', 'Button', 'Badge'] },
    { name: 'ConfirmActionDialog', path: '@/components/creator/ConfirmActionDialog', surfaces: ['creator'], uses: ['Dialog', 'Button'] },
    { name: 'LocalStatusPill', path: '@/components/creator/LocalStatusPill', surfaces: ['creator'], uses: ['Badge'] },
    { name: 'StudioTrendOpsPanel', path: '@/components/design-system/StudioTrendOpsPanel', surfaces: ['studio'] },
    { name: 'CapabilityMapPanel', path: '@/components/design-system/CapabilityMapPanel', surfaces: ['studio'] },
    { name: 'SettingCard', path: '@/components/design-system/SettingCard', surfaces: ['creator', 'studio'] },
    { name: 'PlanCard', path: '@/components/design-system/PlanCard', surfaces: ['billing'] },
  ],
  pageContracts: {
    path: '@/design-system/page-contracts',
    rule: 'Each product route must declare a surface contract before UI migration or new feature work.',
    liveNavRule: 'Public navigation is 发现 / 阅读 / 书城 / 会员. Local Creator, Studio and operator settings remain direct/backstage surfaces.',
  },
  copyBoundary: {
    readerForbidden: ['API', 'OpenAPI', 'PRD', 'fallback', 'demo', 'provider', 'database', 'endpoint', '后台', '后端', '接口', '时间织机'],
    creatorAllowed: ['今日创作路径', '外界回声', '灵感到正文', '本机写作智库', '写作台', '发布包', '本机工作区'],
    studioAllowed: ['质量评分', '发布门禁', '来源策略', '待审章节', '主线', '分支'],
  },
} as const

export type ParallelUniverseDesignSystemRegistry = typeof parallelUniverseDesignSystemRegistry
