export type AgentActionRisk = 'low' | 'medium' | 'high'
export type AgentActionStage =
  | 'navigation'
  | 'echo'
  | 'writing_assist'
  | 'review'
  | 'local_memory'
  | 'publish_bundle'

export type AgentLocalEffect =
  | 'none'
  | 'candidate_record'
  | 'creative_reminder'
  | 'draft_body'
  | 'writing_asset'
  | 'canon_state'
  | 'branch_candidate'
  | 'publish_bundle'

export type AgentPublicEffect =
  | 'none'
  | 'published_content'
  | 'reader_signal_status'

export type AgentActionContract = {
  name: string
  label: string
  route: string
  selector: string
  risk: AgentActionRisk
  stage: AgentActionStage
  shortcut?: string
  commandId?: string
  requiresAuthorConfirmation: boolean
  readsPrivateDraftBody: boolean
  writesLocalData: boolean
  writesPublicData: boolean
  localEffects: readonly AgentLocalEffect[]
  publicEffects: readonly AgentPublicEffect[]
}

export const creatorAgentActions = [
  {
    name: 'open_draft',
    label: '打开草稿',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="open_draft"]',
    risk: 'low',
    stage: 'navigation',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'start_inspiration',
    label: '开始灵感整理',
    route: '/creator/path',
    selector: '[data-agent-action="start_inspiration"]',
    risk: 'low',
    stage: 'navigation',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: false,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'pin_reminder',
    label: '保存创作提醒',
    route: '/creator/echo',
    selector: '[data-agent-action="pin_reminder"]',
    risk: 'medium',
    stage: 'echo',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: false,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['creative_reminder'],
    publicEffects: ['none'],
  },
  {
    name: 'apply_suggestion',
    label: '放入候选区',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="apply_suggestion"]',
    risk: 'medium',
    stage: 'writing_assist',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'select_priority_request',
    label: '挑出今天最值得写的一条',
    route: '/creator',
    selector: '[data-agent-action="select_priority_request"]',
    risk: 'low',
    stage: 'echo',
    shortcut: 'Meta+K',
    commandId: 'pick-request',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: false,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'convert_echo_to_scene',
    label: '把回声整理成一场戏',
    route: '/creator/echo',
    selector: '[data-agent-action="convert_echo_to_scene"]',
    risk: 'medium',
    stage: 'writing_assist',
    shortcut: 'Meta+Enter',
    commandId: 'turn-request-into-scene',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: false,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'generate_candidate_from_instruction',
    label: '按自然语言生成候选',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="generate_candidate_from_instruction"]',
    risk: 'medium',
    stage: 'writing_assist',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'complete_next_beat',
    label: '续写一段',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="complete_next_beat"]',
    risk: 'medium',
    stage: 'writing_assist',
    shortcut: 'Tab',
    commandId: 'complete',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'rewrite_as_action',
    label: '压低解释',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="rewrite_as_action"]',
    risk: 'medium',
    stage: 'writing_assist',
    shortcut: 'Meta+K',
    commandId: 'temper',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'ask_socratic_question',
    label: '追问代价',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="ask_socratic_question"]',
    risk: 'low',
    stage: 'writing_assist',
    shortcut: 'Meta+L',
    commandId: 'question',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'extract_setting_asset',
    label: '沉淀人物、场景和规则',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="extract_setting_asset"]',
    risk: 'medium',
    stage: 'local_memory',
    shortcut: 'Meta+J',
    commandId: 'record',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['writing_asset'],
    publicEffects: ['none'],
  },
  {
    name: 'branch_sandbox',
    label: '支线试写',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="branch_sandbox"]',
    risk: 'medium',
    stage: 'review',
    shortcut: 'Meta+B',
    commandId: 'sandbox',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['branch_candidate'],
    publicEffects: ['none'],
  },
  {
    name: 'inspect_story_impact',
    label: '看影响',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="inspect_story_impact"]',
    risk: 'low',
    stage: 'review',
    shortcut: 'Meta+I',
    commandId: 'state',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'open_suggestion_record',
    label: '看建议依据',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="open_suggestion_record"]',
    risk: 'low',
    stage: 'review',
    shortcut: 'Meta+J',
    commandId: 'record',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'save_local_draft',
    label: '保存草稿',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="save_local_draft"]',
    risk: 'medium',
    stage: 'local_memory',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['draft_body'],
    publicEffects: ['none'],
  },
  {
    name: 'edit_local_manuscript',
    label: '手工修改正文',
    route: '/creator/editor',
    selector: '[data-agent-action="edit_local_manuscript"]',
    risk: 'medium',
    stage: 'writing_assist',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['draft_body'],
    publicEffects: ['none'],
  },
  {
    name: 'start_next_local_chapter',
    label: '开始下一章',
    route: '/creator/editor',
    selector: '[data-agent-action="start_next_local_chapter"]',
    risk: 'medium',
    stage: 'navigation',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['draft_body'],
    publicEffects: ['none'],
  },
  {
    name: 'import_historical_state_candidate',
    label: '导入历史状态候选',
    route: '/creator/editor',
    selector: '[data-agent-action="import_historical_state_candidate"]',
    risk: 'medium',
    stage: 'local_memory',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'start_character_rehearsal',
    label: '开始本机角色排练',
    route: '/creator/editor',
    selector: '[data-agent-action="start_character_rehearsal"]',
    risk: 'medium',
    stage: 'review',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: false,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'save_character_rehearsal_card',
    label: '保存角色排练人物卡',
    route: '/creator/editor',
    selector: '[data-agent-action="save_character_rehearsal_card"]',
    risk: 'medium',
    stage: 'local_memory',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: false,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['writing_asset'],
    publicEffects: ['none'],
  },
  {
    name: 'save_character_rehearsal_setting',
    label: '保存角色排练设定卡',
    route: '/creator/editor',
    selector: '[data-agent-action="save_character_rehearsal_setting"]',
    risk: 'medium',
    stage: 'local_memory',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: false,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['writing_asset'],
    publicEffects: ['none'],
  },
  {
    name: 'confirm_historical_state_candidate',
    label: '确认历史状态候选',
    route: '/creator/editor',
    selector: '[data-agent-action="confirm_historical_state_candidate"]',
    risk: 'high',
    stage: 'local_memory',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['canon_state'],
    publicEffects: ['none'],
  },
  {
    name: 'reject_historical_state_candidate',
    label: '拒绝历史状态候选',
    route: '/creator/editor',
    selector: '[data-agent-action="reject_historical_state_candidate"]',
    risk: 'high',
    stage: 'local_memory',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['candidate_record'],
    publicEffects: ['none'],
  },
  {
    name: 'enter_publish_check',
    label: '进入发布包确认',
    route: '/creator/write/:draftId',
    selector: '[data-agent-action="enter_publish_check"]',
    risk: 'low',
    stage: 'publish_bundle',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['publish_bundle'],
    publicEffects: ['none'],
  },
  {
    name: 'prepare_publish_bundle',
    label: '准备发布包',
    route: '/creator/bundles',
    selector: '[data-agent-action="prepare_publish_bundle"]',
    risk: 'medium',
    stage: 'publish_bundle',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['publish_bundle'],
    publicEffects: ['none'],
  },
  {
    name: 'review_publish_bundle',
    label: '完成发布包审阅',
    route: '/creator/bundles',
    selector: '[data-agent-action="review_publish_bundle"]',
    risk: 'medium',
    stage: 'publish_bundle',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['publish_bundle'],
    publicEffects: ['none'],
  },
  {
    name: 'check_reader_promise',
    label: '检查读者承诺是否兑现',
    route: '/creator/bundles',
    selector: '[data-agent-action="check_reader_promise"]',
    risk: 'low',
    stage: 'publish_bundle',
    shortcut: 'Meta+K',
    commandId: 'reader-promise-check',
    requiresAuthorConfirmation: false,
    readsPrivateDraftBody: true,
    writesLocalData: false,
    writesPublicData: false,
    localEffects: ['none'],
    publicEffects: ['none'],
  },
  {
    name: 'export_publish_bundle',
    label: '生成发布包',
    route: '/creator/bundles',
    selector: '[data-agent-action="export_publish_bundle"]',
    risk: 'high',
    stage: 'publish_bundle',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['publish_bundle'],
    publicEffects: ['none'],
  },
  {
    name: 'confirm_publish_bundle',
    label: '确认发布包内容',
    route: '/creator/bundles',
    selector: '[data-agent-action="confirm_publish_bundle"]',
    risk: 'high',
    stage: 'publish_bundle',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: false,
    localEffects: ['publish_bundle'],
    publicEffects: ['none'],
  },
  {
    name: 'submit_publish_bundle',
    label: '提交发布包',
    route: '/creator/bundles',
    selector: '[data-agent-action="submit_publish_bundle"]',
    risk: 'high',
    stage: 'publish_bundle',
    requiresAuthorConfirmation: true,
    readsPrivateDraftBody: true,
    writesLocalData: true,
    writesPublicData: true,
    localEffects: ['publish_bundle'],
    publicEffects: ['published_content', 'reader_signal_status'],
  },
] as const satisfies readonly AgentActionContract[]

export type CreatorAgentActionName = typeof creatorAgentActions[number]['name']

function indexCreatorAgentActions() {
  const registry = {} as Record<CreatorAgentActionName, AgentActionContract>
  for (const action of creatorAgentActions) registry[action.name] = action
  return registry
}

export const creatorAgentActionByName = indexCreatorAgentActions()

export const blockedCreatorAgentActions = [
  'publish_without_author_confirmation',
  'overwrite_published_canon',
  'upload_private_draft_body',
  'read_credentials',
] as const
