from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol, Any

@dataclass
class ReaderContinueCommand:
    session_id: str
    choice_id: str | None = None
    freeform_intent: str | None = None

class WorldRegistry(Protocol):
    def get_published_world(self, world_id: str) -> dict[str, Any]: ...
    def get_world_version(self, world_version_id: str) -> dict[str, Any]: ...
    def validate_worldpack(self, worldpack: dict[str, Any]) -> dict[str, Any]: ...

class SessionService(Protocol):
    def create_session(self, world_id: str, reader_id: str | None = None) -> dict[str, Any]: ...
    def continue_story(self, command: ReaderContinueCommand) -> dict[str, Any]: ...

class AuthoringService(Protocol):
    def save_draft(self, worldpack: dict[str, Any]) -> dict[str, Any]: ...
    def run_simulation(self, world_id: str) -> dict[str, Any]: ...
    def submit_for_review(self, world_version_id: str) -> dict[str, Any]: ...

class BillingService(Protocol):
    def quote_continue(self, session_id: str, action: str) -> dict[str, Any]: ...
    def meter(self, payload: dict[str, Any]) -> None: ...
