import type {
  CandidateScene,
  CapabilityAlignment,
  GenreKernel,
  HarnessStep,
  OpenSourceAdapter,
  PrdReflectionItem,
  QualityBrakeReport,
  WorldBranch,
  WorldChapter,
  WorldInstance,
  WorldTemplate,
} from './types'

export const genreKernels: GenreKernel[] = [
  {
    id: 'kernel-cosmic-xuanhuan',
    name: '玄幻命运核',
    category: '玄幻 / 仙侠',
    thesis: '力量增长必须伴随愿力、债务和代价，否则世界会崩成纯升级表。',
    pacingModel: '序章低密度，试炼和天劫进入爆发，余波必须回收人物债。',
    eventStructure: '誓愿 -> 诱惑 -> 债务交换 -> 误认 -> 命运试炼 -> 代价落地',
    motiveRules: ['主角困境先于能力展示', '反派必须有可理解的修行逻辑', '每次破境都写入关系债'],
    conflictRules: ['外部战斗必须触发内部取舍', '宗门规则不能只做背景板', '奇遇需要留下可追责的因果'],
    climaxRules: ['高潮前至少回收一个早期伏笔', '胜利要带来新限制', '余波要改变一段关系'],
    timeControls: { baseRate: 0.36, burst: 0.82, decay: 0.42, foreshadowPressure: 0.76 },
    metrics: [
      { label: '节奏弹性', value: 86, tone: 'gold' },
      { label: '命运压力', value: 78, tone: 'cyan' },
      { label: '伏笔回收', value: 73, tone: 'teal' },
    ],
  },
  {
    id: 'kernel-urban-suspense',
    name: '都市悬疑核',
    category: '都市 / 悬疑',
    thesis: '证据链、人物动机和时间线互相校验，选择不是换文本，而是换真相成本。',
    pacingModel: '日常低压铺设线索，关键证据引发短时连锁，随后进入审问和反证余波。',
    eventStructure: '异常物 -> 证词偏差 -> 误导线索 -> 代价选择 -> 公开或隐藏',
    motiveRules: ['每个人都要保护某个秘密', '主角不能免费得到真相', '亲密关系也是证据来源'],
    conflictRules: ['线索必须改变行动', '反转要能回看成立', '每个选择都留下证据损耗'],
    climaxRules: ['高潮揭示一个事实和一个误解', '证据公开会制造新敌人', '沉默会让旧案继续扩散'],
    timeControls: { baseRate: 0.42, burst: 0.74, decay: 0.5, foreshadowPressure: 0.68 },
    metrics: [
      { label: '证据一致', value: 84, tone: 'cyan' },
      { label: '人物可信', value: 81, tone: 'gold' },
      { label: '阅读自然度', value: 77, tone: 'teal' },
    ],
  },
  {
    id: 'kernel-romance-choice',
    name: '情感选择核',
    category: '言情 / 成长',
    thesis: '情感推进来自具体行动和误会修正，不来自空泛告白。',
    pacingModel: '亲密感缓慢累积，误会触发爆发，余波用日常行动修复或撕裂。',
    eventStructure: '靠近 -> 误读 -> 保护/伤害 -> 选择公开 -> 关系重排',
    motiveRules: ['角色表达爱意的方式必须不同', '误会要来自真实价值冲突', '修复需要付行动成本'],
    conflictRules: ['选择必须影响第三方关系', '甜点和伤点交替出现', '沉默也是选择'],
    climaxRules: ['高潮必须逼迫角色说出真实需求', 'HE/BE 都要付出代价', '余波落到生活细节'],
    timeControls: { baseRate: 0.3, burst: 0.58, decay: 0.64, foreshadowPressure: 0.54 },
    metrics: [
      { label: '情绪递进', value: 88, tone: 'rose' },
      { label: '行动表达', value: 80, tone: 'gold' },
      { label: '关系张力', value: 75, tone: 'cyan' },
    ],
  },
  {
    id: 'kernel-history-frontier',
    name: '历史权谋核',
    category: '历史 / 权谋',
    thesis: '历史选择必须让忠诚、民命和合法性互相冲突，胜利不能只靠主角正确。',
    pacingModel: '围城低压建立秩序，密诏版本触发信任爆发，余波落到军民命运。',
    eventStructure: '边城压力 -> 诏书矛盾 -> 旧臣分裂 -> 民命抉择 -> 历史定稿',
    motiveRules: ['忠臣也要有立场盲区', '敌将不能只是压迫者', '每个版本的真相都要服务某种生存逻辑'],
    conflictRules: ['公开真相会破坏秩序', '保全性命会背负骂名', '死守必须写清军民成本'],
    climaxRules: ['高潮必须让百姓成为选择主体', '结局要改变史书叙述', '牺牲不能替代政治后果'],
    timeControls: { baseRate: 0.34, burst: 0.7, decay: 0.56, foreshadowPressure: 0.72 },
    metrics: [
      { label: '立场张力', value: 87, tone: 'gold' },
      { label: '历史可信', value: 83, tone: 'cyan' },
      { label: '牺牲代价', value: 79, tone: 'rose' },
    ],
  },
  {
    id: 'kernel-scifi-memory',
    name: '科幻身份核',
    category: '科幻 / 记忆',
    thesis: '身份悬疑要把记忆、证据和选择拆开，让“我是谁”最终落到行动上。',
    pacingModel: '异常记忆先制造追捕，云端真相引发爆发，结尾把选择权还给个体。',
    eventStructure: '记忆错位 -> 清除追捕 -> 云端探索 -> 自我对峙 -> 选择协议',
    motiveRules: ['AI 角色必须有约束而非万能', '反抗者要像主角的另一种答案', '痛苦记忆不能被写成廉价负担'],
    conflictRules: ['每次取证都提高身份风险', '算法秩序必须有真实好处', '自由选择要付城市级成本'],
    climaxRules: ['高潮同时解决身份与城市规则', '胜利必须保留代价', '开放结局要能扩展系列'],
    timeControls: { baseRate: 0.44, burst: 0.78, decay: 0.48, foreshadowPressure: 0.66 },
    metrics: [
      { label: '身份悬疑', value: 88, tone: 'cyan' },
      { label: '科幻规则', value: 82, tone: 'teal' },
      { label: '存在张力', value: 80, tone: 'gold' },
    ],
  },
]

export const worldTemplates: WorldTemplate[] = [
  {
    id: 'beacon-beyond',
    title: '灯塔之外',
    subtitle: '旗舰连载 / 玄幻悬疑',
    tagline: '当远海灯塔在无月夜重启，你必须决定先救人，还是先保住真相。',
    genre: '玄幻悬疑',
    kernelId: 'kernel-cosmic-xuanhuan',
    mode: 'flagship',
    coverGradient: 'from-cyan-400/30 via-indigo-500/20 to-amber-300/20',
    coverImage: '/parallel-assets/covers/beacon-beyond.jpg',
    coverPosition: '50% 50%',
    openingPremise: '雾海吞掉旧王朝的最后一支船队，灯塔守夜人却在七年后收到船长的求救灯码。',
    protagonistGap: '主角沈星澜能读懂灯码，却一直隐瞒父亲曾参与封塔。',
    initialLocation: '北境雾港，第七灯塔下的潮汐档案室。',
    initialEvent: '灯塔无火自亮，海面同时出现三条互相矛盾的归航线。',
    firstChoicePoint: '公开灯码会引来王庭审判；隐藏灯码能救下唯一幸存者，但会改写主线。',
    chapterCount: '12 章',
    choiceCount: 9,
    audiencePromise: '5 分钟内读到第一个分歧点，10 分钟内看到个人宇宙生成。',
  },
  {
    id: 'black-gate-translator',
    title: '黑门译者',
    subtitle: '创作方向 / 西幻穿越',
    tagline: '现代编辑醒在异大陆矿城，必须翻译一座地下城吐出的死亡祷文。',
    genre: '西方玄幻穿越',
    kernelId: 'kernel-cosmic-xuanhuan',
    mode: 'template',
    coverGradient: 'from-cyan-300/20 via-violet-500/20 to-amber-300/20',
    coverImage: '/parallel-assets/covers/black-gate-translator.svg',
    coverPosition: '50% 50%',
    openingPremise: '异大陆边境矿城把地下城当作灾厄矿井管理，圣堂、佣兵团和矿主都想垄断井底刻文。',
    protagonistGap: '主角许执来自现代中文编辑语境，懂故事结构，却不懂这个世界的神权、契约和生存规矩。',
    initialLocation: '边境矿城、倒扣教堂般的地下城入口、圣堂译写室。',
    initialEvent: '地下城吐出一具失踪佣兵的遗物和一段会改写死因的祷文，所有势力都要求主角按自己的版本翻译。',
    firstChoicePoint: '公开真实译文会得罪圣堂；篡改译文能保命，却会害死唯一会说中文的矿奴少女。',
    chapterCount: '8 章',
    choiceCount: 6,
    audiencePromise: '适合验证西幻穿越、非游戏化地下城、本土网文小人物破局。',
  },
  {
    id: 'rain-bridge',
    title: '雨夜桥边',
    subtitle: '短篇宇宙 / 都市悬疑',
    tagline: '一段桥洞录像能洗清旧案，也会让证人永远消失。',
    genre: '都市悬疑',
    kernelId: 'kernel-urban-suspense',
    mode: 'trial',
    coverGradient: 'from-sky-400/20 via-slate-500/20 to-violet-500/20',
    coverImage: '/parallel-assets/covers/rain-bridge.jpg',
    coverPosition: '50% 50%',
    openingPremise: '旧城区雨夜，失踪记者留下的录音笔开始播放第四个人的呼吸声。',
    protagonistGap: '顾砚总能找到证据，却不敢承认自己曾经删掉过一份关键备份。',
    initialLocation: '废弃高架桥、旧楼天台、凌晨 23:33 的巡逻灯。',
    initialEvent: '证人要求隐藏录像，记者要求立刻公开。',
    firstChoicePoint: '公开证据还是保护证人。',
    chapterCount: '4 章',
    choiceCount: 5,
    audiencePromise: '适合验证证据链、人物一致性和短线分支。',
  },
  {
    id: 'jade-contract',
    title: '玉京契书',
    subtitle: '短篇宇宙 / 仙侠权谋',
    tagline: '一纸婚契能稳住宗门，也会把主角推上替罪祭坛。',
    genre: '仙侠权谋',
    kernelId: 'kernel-cosmic-xuanhuan',
    mode: 'trial',
    coverGradient: 'from-emerald-400/20 via-cyan-500/15 to-amber-300/20',
    coverImage: '/parallel-assets/covers/jade-contract.jpg',
    coverPosition: '50% 50%',
    openingPremise: '玉京城的灵契钟响了三次，每一次都指向不同的未婚人。',
    protagonistGap: '女主知道契书是假的，却需要它救活师门最后一盏魂灯。',
    initialLocation: '玉京外城、天契司、雨后的审契台。',
    initialEvent: '天契司要求当众验契，反派却递来一份能保全师门的伪证。',
    firstChoicePoint: '承认伪证保师门，还是毁契保自身清白。',
    chapterCount: '5 章',
    choiceCount: 6,
    audiencePromise: '适合验证誓愿、债务、关系线和高潮回收。',
  },
  {
    id: 'lotus-lane',
    title: '莲巷来信',
    subtitle: '短篇宇宙 / 情感成长',
    tagline: '那封迟到七年的信，让每一次回复都变成另一种人生。',
    genre: '言情成长',
    kernelId: 'kernel-romance-choice',
    mode: 'trial',
    coverGradient: 'from-rose-400/20 via-violet-400/15 to-cyan-300/20',
    coverImage: '/parallel-assets/covers/lotus-lane.jpg',
    coverPosition: '50% 50%',
    openingPremise: '旧巷拆迁前，女主收到少年时代寄丢的信，邮戳却来自明天。',
    protagonistGap: '她害怕重新选择，因为每次选择都会抹掉一个共同记忆。',
    initialLocation: '莲花巷、旧邮局、雨后的修表铺。',
    initialEvent: '信中写着她明天会见到一个不该还活着的人。',
    firstChoicePoint: '回信改变明天，还是烧掉信保住现在。',
    chapterCount: '4 章',
    choiceCount: 4,
    audiencePromise: '适合验证情绪递进、误会修复和低压分支。',
  },
  {
    id: 'frontier-edict',
    title: '边城密诏',
    subtitle: '故事方向 / 历史架空',
    tagline: '七层密诏把忠臣推成叛将，真正的答案藏在一城人的命里。',
    genre: '历史架空',
    kernelId: 'kernel-history-frontier',
    mode: 'template',
    coverGradient: 'from-amber-400/20 via-slate-500/20 to-red-500/20',
    coverImage: '/parallel-assets/covers/frontier-edict.svg',
    coverPosition: '50% 50%',
    openingPremise: '王朝末年，边城成为最后屏障；明诏要死守，暗诏却命守将开城。',
    protagonistGap: '主角以为自己拿到原诏，却不知道自己已是密诏的第八个转写者。',
    initialLocation: '北境边城、风雪城楼、七层蜡封的军机匣。',
    initialEvent: '敌军压境，使者送来命令开城的密诏，城中旧臣同时拿出不同版本。',
    firstChoicePoint: '遵诏开城能保军民性命；抗诏死守能保忠义名声，却可能让全城陪葬。',
    chapterCount: '8 章',
    choiceCount: 6,
    audiencePromise: '适合验证权谋立场、历史代价和群像分歧。',
  },
  {
    id: 'algorithm-city',
    title: '算法城市',
    subtitle: '故事方向 / 科幻短篇',
    tagline: '当记忆备份指认你杀人，你要证明清白，还是夺回定义自己的权利。',
    genre: '科幻短篇',
    kernelId: 'kernel-scifi-memory',
    mode: 'template',
    coverGradient: 'from-cyan-400/20 via-violet-500/20 to-slate-400/20',
    coverImage: '/parallel-assets/covers/algorithm-city.svg',
    coverPosition: '50% 50%',
    openingPremise: '城市由算法中枢管理，每个人的记忆都会被云端备份和优化。',
    protagonistGap: '主角是最后一类未被优化的人，因此天然会被城市判定为异常。',
    initialLocation: '算法审计署、雨夜记忆诊所、漂浮着备份碎片的云端街区。',
    initialEvent: '主角的备份里多出一段杀人记忆，受害者正是自己的记忆管理员。',
    firstChoicePoint: '公开记忆差异会触发清除程序；删除备份能保命，却会让身份真相永远消失。',
    chapterCount: '6 章',
    choiceCount: 5,
    audiencePromise: '适合验证身份悬疑、短篇强钩子和科幻规则闭环。',
  },
]

export const worldChapters: Record<string, WorldChapter[]> = {
  'beacon-beyond': [
    {
      id: 'beacon-01',
      index: 1,
      title: '第 1 章 雾港重灯',
      kicker: '第七灯塔在无月夜亮起，潮汐档案室里多出一页不存在的航海日志。',
      body:
        '雾从海面爬上石阶时，沈星澜正把第七灯塔的钥匙交还给档案官。钥匙柄冰得反常，像刚从深海捞出来。\n\n' +
        '灯塔已经熄灭七年。那一年，北境最后一支船队消失，王庭宣布灯塔系统永久封存，所有守夜人被迫改名、迁居、沉默。沈星澜本该也是沉默的一部分。\n\n' +
        '可今晚，塔顶没有火，海面却亮起三组灯码。第一组是求救，第二组是归航，第三组只有守夜人家族才看得懂：别让他们上岸。\n\n' +
        '潮汐档案室的铜门在身后自己合上。幸存者名册里多出一个名字，墨迹未干。那是他父亲的旧名。\n\n' +
        '陆白站在水钟旁，手里还夹着半枚火漆。她是雾港最年轻的档案官，也是唯一敢在王庭文书上划红线的人。她没有问沈星澜看见了什么，只把水钟翻过来。细沙没有落下，像整间档案室都被谁按住了呼吸。\n\n' +
        '“灯码如果是真的，议会必须知道。”陆白说。她的声音很轻，却让墙上的航海图同时响了一下。那些被封存的航线从纸背浮出来，像鱼骨，也像旧王朝没有合上的伤口。\n\n' +
        '沈星澜把名册往袖中压了压。他知道公开灯码意味着什么。王庭会在黎明前抵达，旧船队会从传说变成证据，父亲的旧名也会从一页纸变成审判席上的第一句问话。\n\n' +
        '可如果他隐瞒，名册上的人也许还能活到天亮。灯塔外的海雾正在退，礁石间传来木板撞击的声音。有人在远处敲三下，又停三下，那是守夜人之间求救的节奏。\n\n' +
        '档案室最深处的柜门缓缓弹开，露出一排没有编号的铁匣。沈星澜认得那些匣子。守夜人失踪后，王庭把他们的遗物全都封进这里，连名字也从户籍里抹去。现在，其中一只铁匣正在发热。\n\n' +
        '陆白走过去，用袖口垫着指尖掀开匣盖。里面没有遗物，只有一枚被海盐咬白的铜哨。哨身刻着沈星澜父亲留下的字：若第七灯塔再亮，不要相信第一条归航线。\n\n' +
        '海面上，第一条光线忽然变得更亮，像是听懂了这句话。雾港钟楼随即敲响一声。那不是整点钟，而是议会召集令。有人已经看见灯码，也有人正在把消息送往王庭。\n\n' +
        '沈星澜把铜哨攥进掌心，手背被旧盐划出一道细血。灯塔的光从窗格里照进来，在地上切出三条路。每一条都通向海边，也都绕不开那个刚刚浮上纸面的旧名。\n\n' +
        '陆白看着他，没有催促。她把幸存者名册推到桌边，又把议会传令铃放在另一侧。一个动作足够清楚：现在不是判断灯码真假，而是决定先让谁知道真相。',
      choices: [
        {
          id: 'publish-signal',
          label: '公开灯码',
          description: '召集雾港议会，让所有人知道船队仍在归航。',
          branchId: 'public-signal',
          tensionDelta: 22,
          memoryWrite: '灯码被公开，王庭和雾港同时获得归航证据。',
          qualityGate: '需要校验时间线：公开后王庭审判必须提前。',
        },
        {
          id: 'hide-survivor',
          label: '隐藏幸存者名册',
          description: '先找到名册上的人，再决定是否让灯塔回到主线。',
          branchId: 'hidden-survivor',
          tensionDelta: 17,
          memoryWrite: '沈星澜私藏名册，个人宇宙写入隐瞒债。',
          qualityGate: '需要校验人物一致性：隐瞒必须付出关系代价。',
        },
      ],
    },
  ],
  'rain-bridge': [
    {
      id: 'rain-01',
      index: 1,
      title: '第 1 章 桥洞录像',
      kicker: '旧案证人只愿在雨夜出现，而录像公开前只剩一次备份机会。',
      body:
        '顾砚把录音笔放在桥洞水泥台上，红灯闪了三下。第四段呼吸声夹在雨声里，轻得像有人站在他背后。\n\n' +
        '林秋没有看他，只盯着手机里那段模糊录像。画面里，证人从旧楼侧门跑出，身后那个人的伞面压得很低。边年少帅说，公开它，旧案今晚就会翻盘。\n\n' +
        '证人却发来最后一条消息：如果视频出现，我就不会活到天亮。',
      choices: [
        {
          id: 'rain-public-video',
          label: '公开录像',
          description: '让媒体和旧案家属立刻看到证据。',
          branchId: 'media-fire',
          tensionDelta: 26,
          memoryWrite: '录像公开，证人安全急剧下降。',
          qualityGate: '需要校验证据链损耗和媒体介入后的追责节奏。',
        },
        {
          id: 'rain-save-witness',
          label: '先救证人',
          description: '关闭手机，转移证人，延后公开。',
          branchId: 'witness-first',
          tensionDelta: 18,
          memoryWrite: '证人存活概率上升，林秋信任下降。',
          qualityGate: '需要校验人物关系：林秋必须对隐瞒产生反应。',
        },
      ],
    },
  ],
  'jade-contract': [
    {
      id: 'jade-01',
      index: 1,
      title: '第 1 章 三响灵契',
      kicker: '天契司的钟响了三次，城中每个人都听见了不同的名字。',
      body:
        '审契台上的雨刚停，玉牌却还在发烫。闻照雪跪在青石中央，看见自己的名字被写进三份婚契，每一份都能救师门，也都能杀她。\n\n' +
        '天契司要她当众验契。反派递来的伪证能保住魂灯，但会让她从此欠下一条不能还的命。',
      choices: [
        {
          id: 'jade-fake-contract',
          label: '承认伪证',
          description: '保住师门魂灯，把自己锁进契约。',
          branchId: 'false-vow',
          tensionDelta: 21,
          memoryWrite: '伪契成形，师门暂安，主角背负假誓。',
          qualityGate: '需要写入誓愿债，并在高潮前触发反噬。',
        },
        {
          id: 'jade-break-contract',
          label: '当众毁契',
          description: '保住自身清白，但让师门暴露在审判下。',
          branchId: 'broken-vow',
          tensionDelta: 24,
          memoryWrite: '契书毁坏，魂灯进入倒计时。',
          qualityGate: '需要校验外部危机和内在愿力同步推进。',
        },
      ],
    },
  ],
  'lotus-lane': [
    {
      id: 'lotus-01',
      index: 1,
      title: '第 1 章 明日邮戳',
      kicker: '旧邮局的信箱吐出一封七年前的信，邮戳日期却是明天。',
      body:
        '莲花巷拆迁公告贴满墙面时，许知夏在旧邮局门口捡到那封信。信封边角被雨泡软，字迹却新得像刚刚写下。\n\n' +
        '信里只有一句话：明天别去修表铺，否则你会再次错过他。\n\n' +
        '她想起七年前没有寄出的回信，想起那个再也没回来的人，也想起自己终于学会不回头的这些年。',
      choices: [
        {
          id: 'lotus-reply',
          label: '回信给明天',
          description: '承认自己还想改变，把选择写进未来。',
          branchId: 'reply-tomorrow',
          tensionDelta: 16,
          memoryWrite: '未来被回复，旧记忆开始松动。',
          qualityGate: '需要校验情绪递进，不能直接跳到重逢。',
        },
        {
          id: 'lotus-burn',
          label: '烧掉来信',
          description: '保住现在的生活，不让过去重新开口。',
          branchId: 'burn-letter',
          tensionDelta: 13,
          memoryWrite: '来信被烧毁，但邮戳灰烬保留异常。',
          qualityGate: '需要让沉默成为选择，而不是无事发生。',
        },
      ],
    },
  ],
  'frontier-edict': [
    {
      id: 'frontier-01',
      index: 1,
      title: '第 1 章 七层蜡封',
      kicker: '敌军压到城外三里时，边城守将收到一封命他开城投降的密诏。',
      body:
        '风雪把城楼吹得像一面将碎未碎的鼓。顾怀烽站在垛口前，看见敌军火把连成一条赤线，正一点点把北境最后的夜色烧亮。\n\n' +
        '军机匣在他掌心里发冷。蜡封一共七层，最外层是当今天子的玺，最内层却露出先帝旧印的边角。传诏使者跪在雪里，只说四个字：即刻开城。\n\n' +
        '城下百姓已经被召到内街，妇孺的哭声压得很低，像怕惊动城外的刀。军师沈砚没有看密诏，只看顾怀烽的手。他知道那只手握过先帝托孤的剑，也握过边城三万户的生死册。\n\n' +
        '第一层蜡封剥开，诏书写着开城。第二层却写着死守。第三层的字迹被水浸过，只剩“保全”二字。每剥一层，城楼上的将领就安静一分。\n\n' +
        '敌将派来的劝降书也在这时送到。信封上没有官印，只有顾怀烽少年时与那人同窗读书时用过的旧号：别让百姓替皇帝证明忠诚。\n\n' +
        '顾怀烽把七层密诏摊在城砖上，雪落在不同版本的字句之间。忠诚忽然不再是一条路，而像七把刀，每一把都指向不同的人。',
      choices: [
        {
          id: 'frontier-open-gate',
          label: '公布密诏并开城',
          description: '保住军民性命，把骂名留给自己承担。',
          branchId: 'edict-open-gate',
          tensionDelta: 25,
          memoryWrite: '边城军民得知诏书真相，守将背负开城骂名。',
          qualityGate: '后续写作要照顾民命代价和史书评价，不能把开城写成轻松胜利。',
        },
        {
          id: 'frontier-resist',
          label: '撕毁密诏死守',
          description: '守住忠义名声，也让边城进入破城倒计时。',
          branchId: 'edict-last-stand',
          tensionDelta: 28,
          memoryWrite: '密诏被撕毁，边城进入死守线，军民命运被压上城楼。',
          qualityGate: '后续写作要让军民成本可见，避免只写主角悲壮。',
        },
      ],
    },
  ],
  'algorithm-city': [
    {
      id: 'algorithm-01',
      index: 1,
      title: '第 1 章 十一分差异',
      kicker: '记忆一致性超过十个百分点偏差，城市就会把你判定为非法复制人。',
      body:
        '凌晨两点，算法审计署的玻璃墙同时亮起红光。林述的记忆报告悬在空中，差异值停在 11.7%。再往上跳一次，清除程序就会自动启动。\n\n' +
        '报告里写着他昨晚杀了一个人。受害者名叫白栀，是他的记忆备份管理员。林述记得自己整晚都在家里睡觉，甚至记得窗外广告屏循环播放了三十七遍同一句话：遗忘痛苦，是城市给你的福利。\n\n' +
        '搭档 AI 以人形投影站在门口，声音像被压低的系统提示：“你有六分钟解释这段记忆。”\n\n' +
        '林述没有解释。他调出云端备份，发现杀人片段里的人确实用着他的脸，却在镜头最后抬头笑了一下。那个笑不是他会有的表情，更像另一个熟悉他全部弱点的人借走了身体。\n\n' +
        '清除倒计时开始时，地下记忆黑客组织发来一条匿名信息：别删备份。那不是罪证，是你活过的另一半。',
      choices: [
        {
          id: 'algorithm-disclose',
          label: '公开记忆差异',
          description: '请求城市审判，让所有证据进入公开记录。',
          branchId: 'memory-disclosed',
          tensionDelta: 23,
          memoryWrite: '记忆差异被公开，清除程序提前进入人工复核。',
          qualityGate: '后续写作要同时推进证据链和身份风险。',
        },
        {
          id: 'algorithm-delete',
          label: '删除异常备份',
          description: '暂时逃过清除程序，但可能抹掉唯一能证明身份的线索。',
          branchId: 'memory-deleted',
          tensionDelta: 20,
          memoryWrite: '异常备份被删除，主角保住当下身份，云端真相断裂。',
          qualityGate: '后续写作要让删除带来不可逆代价。',
        },
      ],
    },
  ],
}

export const worldBranches: WorldBranch[] = [
  {
    id: 'mainline',
    templateId: 'beacon-beyond',
    name: '主线',
    status: 'canon',
    tone: '雾港取证',
    summary: '沈星澜暂时保留灯码，等待确认幸存者身份。',
    divergence: 12,
    stability: 86,
    readingProgress: 18,
    diffHighlights: ['灯塔重启未公开', '父亲旧名进入档案', '王庭尚未介入'],
  },
  {
    id: 'public-signal',
    templateId: 'beacon-beyond',
    name: '公开灯码线',
    status: 'candidate',
    tone: '审判逼近',
    summary: '雾港议会得知船队归航，王庭审判提前到黎明。',
    divergence: 52,
    stability: 64,
    readingProgress: 22,
    unlockedByChoiceId: 'publish-signal',
    diffHighlights: ['议会封锁码头', '王庭特使提前抵达', '幸存者被迫暴露'],
  },
  {
    id: 'hidden-survivor',
    templateId: 'beacon-beyond',
    name: '隐藏幸存者线',
    status: 'active',
    tone: '私藏债务',
    summary: '沈星澜私藏名册，先去找名册上的人。',
    divergence: 44,
    stability: 68,
    readingProgress: 22,
    unlockedByChoiceId: 'hide-survivor',
    diffHighlights: ['守夜人债务写入记忆', '档案官开始怀疑', '灯塔余光持续升高'],
  },
  {
    id: 'media-fire',
    templateId: 'rain-bridge',
    name: '媒体燃线',
    status: 'candidate',
    tone: '高压公开',
    summary: '录像公开引爆旧案，证人被迫转移。',
    divergence: 66,
    stability: 48,
    readingProgress: 28,
    unlockedByChoiceId: 'rain-public-video',
    diffHighlights: ['媒体介入', '证人安全下降', '边年少帅成为嫌疑人'],
  },
  {
    id: 'witness-first',
    templateId: 'rain-bridge',
    name: '证人优先线',
    status: 'active',
    tone: '低声护送',
    summary: '顾砚关闭手机，先转移证人。',
    divergence: 42,
    stability: 61,
    readingProgress: 28,
    unlockedByChoiceId: 'rain-save-witness',
    diffHighlights: ['证人存活', '林秋信任下降', '录像仍未公开'],
  },
  {
    id: 'false-vow',
    templateId: 'jade-contract',
    name: '假誓线',
    status: 'candidate',
    tone: '愿债成形',
    summary: '闻照雪承认伪契，师门魂灯暂时稳定。',
    divergence: 58,
    stability: 54,
    readingProgress: 24,
    unlockedByChoiceId: 'jade-fake-contract',
    diffHighlights: ['伪契进入主线待审稿', '魂灯稳定', '天契司留下证据'],
  },
  {
    id: 'reply-tomorrow',
    templateId: 'lotus-lane',
    name: '回信明日线',
    status: 'candidate',
    tone: '温柔改写',
    summary: '许知夏把回信投进旧邮筒，明天开始偏移。',
    divergence: 36,
    stability: 72,
    readingProgress: 25,
    unlockedByChoiceId: 'lotus-reply',
    diffHighlights: ['旧记忆松动', '修表铺提前开门', '未来邮戳失真'],
  },
  {
    id: 'edict-open-gate',
    templateId: 'frontier-edict',
    name: '开城留名线',
    status: 'candidate',
    tone: '理性背负',
    summary: '顾怀烽公布密诏真相，选择开城保全军民。',
    divergence: 62,
    stability: 55,
    readingProgress: 20,
    unlockedByChoiceId: 'frontier-open-gate',
    diffHighlights: ['军民得知密诏真相', '守将背负骂名', '王朝合法性开始松动'],
  },
  {
    id: 'edict-last-stand',
    templateId: 'frontier-edict',
    name: '抗诏死守线',
    status: 'candidate',
    tone: '悲壮守城',
    summary: '密诏被撕毁，边城进入破城倒计时。',
    divergence: 71,
    stability: 48,
    readingProgress: 20,
    unlockedByChoiceId: 'frontier-resist',
    diffHighlights: ['城防全面启动', '百姓被卷入抉择', '敌将旧情转为战场压力'],
  },
  {
    id: 'memory-disclosed',
    templateId: 'algorithm-city',
    name: '公开差异线',
    status: 'candidate',
    tone: '身份审判',
    summary: '林述公开记忆差异，让城市审判接管证据。',
    divergence: 58,
    stability: 57,
    readingProgress: 18,
    unlockedByChoiceId: 'algorithm-disclose',
    diffHighlights: ['清除程序进入复核', 'AI 搭档权限上升', '备份人格留下公开痕迹'],
  },
  {
    id: 'memory-deleted',
    templateId: 'algorithm-city',
    name: '删除备份线',
    status: 'active',
    tone: '真相断裂',
    summary: '异常备份被删除，主角暂时保住身份，却失去一段关键证据。',
    divergence: 49,
    stability: 63,
    readingProgress: 18,
    unlockedByChoiceId: 'algorithm-delete',
    diffHighlights: ['身份保住', '证据断裂', '记忆黑客组织转为主动接触'],
  },
]

export const activeInstance: WorldInstance = {
  id: 'reader-demo-instance',
  templateId: 'beacon-beyond',
  readerName: '首批体验读者',
  currentBranchId: 'hidden-survivor',
  canonStatus: 'candidate',
  memory: ['读者看见第七灯塔重启', '父亲旧名进入潮汐档案', '幸存者名册被临时隐藏'],
  relationships: [
    { name: '沈星澜 / 档案官陆白', state: '互相试探', pressure: 68 },
    { name: '沈星澜 / 失踪父亲', state: '隐瞒债浮现', pressure: 81 },
    { name: '雾港 / 王庭', state: '审判将至', pressure: 74 },
  ],
}

export const qualityReports: QualityBrakeReport[] = [
  {
    id: 'quality-hidden-survivor',
    title: '隐藏幸存者名册',
    decision: 'rewrite',
    score: 82,
    candidateStatus: 'candidate',
    metrics: [
      { label: '语言节奏', value: 86, detail: '开场低密度，选择后进入短爆发。' },
      { label: '人物一致性', value: 80, detail: '沈星澜的隐瞒与父亲旧债一致。' },
      { label: '时间一致性', value: 78, detail: '王庭审判未提前，符合隐藏线。' },
      { label: '伏笔连贯', value: 84, detail: '灯码、旧名、幸存者名册互相挂钩。' },
      { label: '阅读自然度', value: 81, detail: '抽象句较少，物件锚点稳定。' },
    ],
    issues: ['下一段需要让档案官产生可见怀疑，否则隐瞒代价不足。'],
    nextAction: '保持待审，补一段档案官追问后再允许转入分支。',
  },
  {
    id: 'quality-public-signal',
    title: '公开灯码',
    decision: 'pass',
    score: 88,
    candidateStatus: 'canon_ready',
    metrics: [
      { label: '语言节奏', value: 84, detail: '议会和王庭形成清晰爆发。' },
      { label: '人物一致性', value: 86, detail: '公开符合守夜人的责任冲动。' },
      { label: '时间一致性', value: 90, detail: '黎明审判与灯码传播速度匹配。' },
      { label: '伏笔连贯', value: 89, detail: '旧船队、归航线和灯塔封存被同时激活。' },
      { label: '阅读自然度', value: 88, detail: '物件和行动比例健康。' },
    ],
    issues: [],
    nextAction: '允许进入主线复核，等待创作者确认。',
  },
]

export const candidateScenes: CandidateScene[] = [
  {
    id: 'scene-hidden-survivor',
    title: '待审片段：潮汐档案室',
    status: 'candidate',
    branchId: 'hidden-survivor',
    sourceChoiceId: 'hide-survivor',
    qualityReportId: 'quality-hidden-survivor',
    body:
      '沈星澜把名册夹进外衣内侧时，潮汐档案室的水钟停了一息。陆白抬头看他，像是听见了纸页摩擦胸骨的声音。\n\n' +
      '“守夜人不该替灯塔做决定。”陆白说。\n\n' +
      '沈星澜没有回答。他知道自己不是在替灯塔做决定，而是在替一个可能还活着的人争取天亮以前的时间。',
  },
  {
    id: 'scene-public-signal',
    title: '待审片段：议会钟声',
    status: 'canon_ready',
    branchId: 'public-signal',
    sourceChoiceId: 'publish-signal',
    qualityReportId: 'quality-public-signal',
    body:
      '议会钟声从雾里撞出来时，码头上的人都抬起了头。三条归航线被投到白墙上，像三道互相否认的伤口。\n\n' +
      '沈星澜站在灯塔下，第一次没有替父亲藏起旧名。王庭特使的马车也在这时驶进雾港，车窗后亮着同样的灯码。',
  },
]

export const harnessSteps: HarnessStep[] = [
  { id: 'plan', label: '确认目标', detail: '读取类型规则和当前世界记忆，确定这一章要偿还的叙事债。', status: 'done' },
  { id: 'draft', label: '生成初稿', detail: '先形成待审章节，保留给创作者检查。', status: 'done' },
  { id: 'tool', label: '检查稿件', detail: '并行检查事件节奏、人物一致性、伏笔回收和语言自然度。', status: 'active' },
  { id: 'observe', label: '查看结果', detail: '把评分、问题和下一步建议整理成创作室状态。', status: 'waiting' },
  { id: 'fix', label: '修订片段', detail: '不达标的片段继续保留待审，并提示补代价或改节奏。', status: 'waiting' },
  { id: 'confirm', label: '发布确认', detail: '创作者或运营确认后才允许进入主线或分支。', status: 'blocked' },
]

export const openSourceAdapters: OpenSourceAdapter[] = [
  {
    id: 'sillytavern',
    name: 'SillyTavern',
    license: 'AGPL-3.0',
    role: '角色记忆体验参考适配器',
    status: 'license_gate',
    risk: 'AGPL 需要单独法律评估，首版不直接复制代码。',
    nextAction: '只保留角色记忆体验参考，不进入读者体验。',
  },
  {
    id: 'langgraph',
    name: 'LangGraph / Dify',
    license: '多许可证开源',
    role: '长任务编排和人工审批参考',
    status: 'planned',
    risk: '会增加长任务编排和状态持久化复杂度。',
    nextAction: '先把章节处理流程稳定在创作室。',
  },
  {
    id: 'comfyui',
    name: 'ComfyUI / InvokeAI',
    license: '开源适配',
    role: '人物肖像和场景插画生成',
    status: 'planned',
    risk: '需要 GPU/队列/内容审核。',
    nextAction: '首版使用产品卡片，不调用生成服务。',
  },
  {
    id: 'inkos',
    name: 'NovelForge / InkOS',
    license: '结构参考',
    role: '结构化卡片驱动作品设定参考',
    status: 'ready',
    risk: '只吸收结构思路，不复制实现。',
    nextAction: '映射到题材规则和作品设定。',
  },
]

export const capabilityAlignments: CapabilityAlignment[] = [
  {
    id: 'reader-home',
    title: '商业冷启动首页',
    frontendEntry: '/',
    productSurface: ['世界模板', '类型内核', '读者路径'],
    mode: 'interactive_prototype',
    readerPromise: '第一屏直接把读者带到旗舰宇宙和试玩世界，而不是空白创作表单。',
    implementationBoundary: '首屏呈现真实产品体验，工程细节收在幕后。',
  },
  {
    id: 'reader-template-demo',
    title: '模板宇宙阅读器',
    frontendEntry: '/story?world=<世界模板编号>',
    productSurface: ['/v1/reader/sessions', '/v1/reader/continue', '/v1/reader/snapshot', '/v1/scene/advance', '选择点', '世界实例', '事件节奏', '故事稳定度'],
    mode: 'interactive_prototype',
    readerPromise: '读者能真实阅读、选择、看到个人世界线、角色记忆和质量反馈。',
    implementationBoundary: '所有选择都在前端状态中可见更新，避免只做静态说明。',
  },
  {
    id: 'creator-dialogue',
    title: '对话创作',
    frontendEntry: '/create',
    productSurface: ['/v1/creator/dialogue/sessions', '/v1/creator/dialogue/sessions/{session_id}', '/v1/creator/dialogue/sessions/{session_id}/turns'],
    mode: 'interactive_prototype',
    readerPromise: '创作者输入一句故事种子后，系统先写正文，再追问最多两个必要问题。',
    implementationBoundary: '前端优先调用后端创作会话；后端不可用时只显示明确的本地草稿降级。',
  },
  {
    id: 'world-discovery',
    title: '世界发现与筛选',
    frontendEntry: '/library',
    productSurface: ['/v1/reader/library/worlds', '旗舰宇宙', '可试玩宇宙', '故事方向储备'],
    mode: 'interactive_prototype',
    readerPromise: '读者可以按类型筛选宇宙，并从任何卡片进入阅读。',
    implementationBoundary: '世界库只展示可玩的内容，不展示不可用服务状态。',
  },
  {
    id: 'market-trends',
    title: '热门题材索引',
    frontendEntry: '/ /library /create /studio',
    productSurface: ['/v1/market/trends', '/v1/market/trends/scan', '/v1/market/trends/cron/weekly', '/v1/market/trends/cron/monthly'],
    mode: 'service_contract',
    readerPromise: '首页、书城和创作页共享同一套题材趋势排序；刷新和调度细节只进入创作室。',
    implementationBoundary: '公开页只展示推荐结果，Studio 才展示扫描合同和刷新按钮。',
  },
  {
    id: 'reader-membership',
    title: '会员权益中心',
    frontendEntry: '/settings',
    productSurface: ['/v1/account/snapshot', '/v1/account/merge/preview', '/v1/account/merge/confirm', '/v1/account/data/export', '/v1/account/delete/preview', '/v1/account/delete/confirm', '/v1/reader/subscription', '/v1/reader/checkout/start', '/v1/reader/checkout/{checkout_session_id}/status', '/v1/reader/checkout/return'],
    mode: 'service_contract',
    readerPromise: '读者可以查看当前权益、阅读次数、创作额度、阅读进度和创作草稿，并管理自己的账号数据。',
    implementationBoundary: '页面只展示可恢复动作、档案状态、导出和删除账号，不展示支付服务字段、迁移状态或运营排障信息。',
  },
  {
    id: 'my-worldline',
    title: '我的宇宙线',
    frontendEntry: '/story 右侧反馈',
    productSurface: ['分支卡片', '宇宙线图谱', '分享预览'],
    mode: 'interactive_prototype',
    readerPromise: '读者能在阅读页看到自己的分支、分歧点和保存状态。',
    implementationBoundary: '我的宇宙线收敛到阅读器右侧，不再作为独立社区入口。',
  },
  {
    id: 'character-memory',
    title: '角色关系与记忆',
    frontendEntry: '/story 右侧反馈',
    productSurface: ['记忆内核', '关系压力', '角色记忆反馈'],
    mode: 'interactive_prototype',
    readerPromise: '读者能在不离开正文的情况下看到选择如何改变角色关系、记忆和下一章风险。',
    implementationBoundary: '角色反馈由当前选择和记忆状态驱动，不再使用独立对话页承载。',
  },
  {
    id: 'studio-ops',
    title: '创作运营工作台',
    frontendEntry: '/studio',
    productSurface: ['类型配置', '角色记忆', '发布检查', '适配器登记'],
    mode: 'studio_contract',
    readerPromise: '创作端能看到章节工作流、发布检查、适配器登记和发布确认的产品化形态。',
    implementationBoundary: '工程细节收进创作室，不进入普通读者路径。',
  },
  {
    id: 'canon-quality-second-phase',
    title: '正史提交服务化',
    frontendEntry: '选择抽屉 / 创作室发布检查',
    productSurface: ['/v1/quality/evaluate', '/v1/canon/commit', '/v1/scene/advance', '/v1/reader/snapshot', '/v1/timeline/worldlines/{id}/loom'],
    mode: 'studio_contract',
    readerPromise: '用户能看见分支确认与发布检查的产品逻辑，工程团队能沿已验证边界继续服务化。',
    implementationBoundary: '前端仍以预览状态展示候选/转正逻辑；发布前必须把这些边界接入 UI 数据流。',
  },
]

export const prdReflectionItems: PrdReflectionItem[] = [
  {
    id: 'reader-first-entry',
    requirement: '首页第一屏必须让读者直接开始阅读旗舰宇宙，而不是先填复杂设定。',
    status: 'done',
    surface: '/',
    current: '首屏主 CTA 指向《灯塔之外》，试玩宇宙和创作入口被分层放置。',
    gap: '无阻塞；仍需后续用真实用户点击数据验证冷启动转化。',
    next: '接入埋点后观察开始阅读率、选择完成率和创作入口转化。',
  },
  {
    id: 'three-zone-reader',
    requirement: '阅读页采用左侧世界/章节索引、中间 680-760px 浅色正文、右侧按需抽屉。',
    status: 'done',
    surface: '/story',
    current: '桌面三分区已落地，移动端折叠索引和宇宙抽屉，正文面板限制在 760px。',
    gap: '无阻塞；移动端仍需更多真实长文本压力测试。',
    next: '扩展到 8-12 章后继续检查滚动、抽屉和章节跳转。',
  },
  {
    id: 'genre-world-contracts',
    requirement: '前端需要显式表达 GenreKernel、WorldTemplate、WorldInstance 和候选场景合同。',
    status: 'done',
    surface: '/studio / /library / /story',
    current: 'TypeScript 合同和稳定 mock 数据已驱动世界库、阅读器、剧情节奏与质量面板。',
    gap: '当前合同未由 OpenAPI 生成，后端还不是唯一事实源。',
    next: '后端接口稳定后用 OpenAPI codegen 替换手写前端合同。',
  },
  {
    id: 'time-engine-demo',
    requirement: '时间引擎要体现非齐次泊松/Hawkes 风格的平缓、爆发和余波。',
    status: 'partial',
    surface: '/story / /v1/timeline/worldlines/{id}/loom',
    current: '前端确定性 simulator 已展示事件密度；后端现在可返回 reader session 的持久化运行事件和密度摘要。',
    gap: '后端尚未拟合非齐次泊松/Hawkes 参数，不能声明真实可训练时间引擎。',
    next: '把当前 observed runtime trace 升级为参数化事件密度服务，并把参数写入世界实例。',
  },
  {
    id: 'quality-brake',
    requirement: '所有生成文本先为 candidate，经过质量评价与确认后才能 canon 或 branch。',
    status: 'partial',
    surface: '/story / /studio / /v1/quality/evaluate / /v1/canon/commit',
    current: '读者端展示轻量叙事稳定度，Studio 展示 candidate/canon_ready/branch_only；后端已提供质量评价和确认后提交 ledger 的合同。',
    gap: '前端尚未把 Studio 发布按钮接到服务端提交；正史 ledger 仍是审计文件，不是完整世界版本发布系统。',
    next: '把发布检查接入 /v1/quality/evaluate 和 /v1/canon/commit，再接世界版本发布表。',
  },
  {
    id: 'backend-interface-match',
    requirement: '前后端入口必须对应；没有接上的能力要降级说明，不能伪造成生产能力。',
    status: 'partial',
    surface: 'API / Studio',
    current: '首发前端入口仍只依赖稳定 reader/library/creator 合同；PRD 二期接口已进入 OpenAPI 并有后端测试覆盖。',
    gap: '前端还没有解除 story/studio 的本地 demo 数据源，不能声明完整后端闭环。',
    next: '逐个把 /reader/snapshot、/scene/advance、/quality/evaluate、/canon/commit 接进 UI，再移除对应本地演示数据。',
  },
  {
    id: 'open-source-adapters',
    requirement: 'SillyTavern、LangGraph/Dify、ComfyUI/InvokeAI 等开源能力需要可控集成。',
    status: 'partial',
    surface: '/studio',
    current: '已做 Adapter Registry 与能力卡，SillyTavern AGPL 被 license gate 锁住。',
    gap: '首版没有 vendor 或直接调用这些项目，视觉和对话体验仅作为产品参考。',
    next: '逐项通过许可、部署、审核和成本门禁后再接入真实适配器。',
  },
  {
    id: 'full-backend-loop',
    requirement: 'Harness/Agent Eval 循环最终要真实执行 plan/draft/tool/observe/fix/confirm。',
    status: 'partial',
    surface: 'Backend / Ops / /v1/scene/advance',
    current: '/v1/scene/advance 已复用 reader continuation，返回 candidate scene、quality brake 和 plan/draft/tool/confirm trace。',
    gap: 'fix/retry、自迭代 learned evaluator/reranker 与可审计 job/event log 仍未进入生产门禁。',
    next: '把失败修复循环和人工确认状态落到服务端 job/event log，再接 learned shadow 结果。',
  },
]

export function isWorldTemplateId(templateId: string): boolean {
  return worldTemplates.some(template => template.id === templateId)
}

export function getTemplateById(templateId: string): WorldTemplate {
  return worldTemplates.find(template => template.id === templateId) || worldTemplates[0]
}

export function getKernelById(kernelId: string): GenreKernel {
  return genreKernels.find(kernel => kernel.id === kernelId) || genreKernels[0]
}

export function getBranchesForTemplate(templateId: string): WorldBranch[] {
  return worldBranches.filter(branch => branch.templateId === templateId)
}

export function getChapterForTemplate(templateId: string): WorldChapter {
  return worldChapters[templateId]?.[0] || worldChapters['beacon-beyond'][0]
}
